### Librerias:

In [1]:
import pandas as pd
import numpy as np

# EJERCICIO 1

    
    Crea una matriz con ayuda numpy:

        1) Cuya matriz contenga 4 filas por 4 columnas de ceros

        2) Apartir de la matriz de ceros crea la matriz identidad

In [7]:
matriz_0 = np.zeros((4,4))

    
    Crea una matriz con ayuda numpy:

        1) Cuya matriz contenga 4 filas por 4 columnas de ceros

        2) Apartir de la matriz de ceros crea la matriz identidad

In [8]:
matriz_0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
for i,j in enumerate(matriz_0):
    for i1,j1 in enumerate(matriz_0):
        if i==i1:
            matriz_0[i][i1]= 1
matriz_0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# EJERCICIO 2

    Crea una matriz con ayuda numpy:

        Primera fila contenga: 3, 6, 8
        Segunda fila contenga: 20, 5, 7
        Tercera fila contenga: 10, 14, 1

In [11]:
matriz_1 = np.array([
    [3, 6, 8],
    [20, 5, 7],
    [10, 14, 1]
])
matriz_1

array([[ 3,  6,  8],
       [20,  5,  7],
       [10, 14,  1]])

In [13]:
matriz_2 = matriz_1.T
matriz_2 

array([[ 3, 20, 10],
       [ 6,  5, 14],
       [ 8,  7,  1]])

In [15]:
matriz_22 = np.transpose(matriz_1)
matriz_22

array([[ 3, 20, 10],
       [ 6,  5, 14],
       [ 8,  7,  1]])

In [17]:
matriz_1.shape

(3, 3)

In [18]:
matriz_1.size

9

In [19]:
np.all(matriz_1<0)

False

In [20]:
np.any(matriz_1>10)

True

In [21]:
np.linspace(matriz_1.min(), matriz_1.max(),5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [22]:
if (7 in matriz_1)== True:
    print('La matriz contiene el valor 7')
else:
    print('La matriz NO contiene el valor 7')

La matriz contiene el valor 7


In [23]:
matriz_3 = np.ravel(matriz_1)
matriz_3

array([ 3,  6,  8, 20,  5,  7, 10, 14,  1])

In [31]:
matriz_4 = np.array([])
for i in matriz_1:
    for j in i:
        matriz_4 = np.append(matriz_4,j)

matriz_4

array([ 3.,  6.,  8., 20.,  5.,  7., 10., 14.,  1.])

In [34]:
matriz_5 = matriz_1.flatten()
matriz_5 = pow(matriz_5,3)
matriz_5

array([  27,  216,  512, 8000,  125,  343, 1000, 2744,    1], dtype=int32)